### ISSUE TITLE
Signup Page having too many fields

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#126]
Right now Signup page is show profile creation page. We need to have just below fields. 
1) First Name
2)  Last Name
3) Mobile : optional
4) username
5) email id
6) Password
7) Confirm password.

@ultimatecoder Looks like this bug is up after you code changes. Can you please fix it today ?

**Comment by ultimatecoder** [comment]
@vnbang2003  Actually done this discussion with @theskumar over IRC before making final changes. I took his advice to put these fields here. If we consider normal website flow, Signup page contains minimal important things. Which includes some important part of profile as well as system. As you know, with my previous merge we had removed profile create view because it is overkill.
I believe, it will be good to force user to to provide important fields at signup rather then giving them choice to add after login.

**Comment by ultimatecoder** [comment]
@vnbang2003 : Consider Example, After signing up with only username, password, email, firstname, lastname. Users are bit lazy to update important part of system which is their **location, User type and Interested Topics, and interested location**. So, it is better to ask them once they are signing up and allow them to edit it after rather then giving another choice.

**Comment by vnbang2003** [comment]
@ultimatecoder We are enforcing user to fill profile if not created this will work for both Social login and signup. Signup should be very minimal possible will not be interested to fill big form.

**Comment by ultimatecoder** [comment]
@vnbang2003 : On a nod of signup user from other social login, I will be agree with you! I will fix this.

**Comment by vnbang2003** [comment]
@ultimatecoder Can you make this as priority as it blocker.

**Comment by ultimatecoder** [comment]
@vnbang2003  PR is done. Requesting to check. Thank you.
