### ISSUE TITLE
Resize Profile Picture before storing to database 

### ISSUE THREAD

**Issue by ultimatecoder** [pythonindia/wye#147]
* **Problem:** Presently, we are not converting any image uploaded as profile picture. As a result we have to store actual image with having any size at the data base. This can overload database without any specific reason.

* **Solution:** Allow User to upload any size of image but re-size, render image to smaller size before finally storing it to the database.

**Comment by vnbang2003** [comment]
@ultimatecoder Let push to Version 0.2 as it not critical right now

**Comment by theskumar** [comment]
I just want to add here that 
- there is no overhead on database if the original photos are saved, it will only add to more disk requirement.
- The "ideal" solution would be resize the uploaded images client size to something reasonable size, say 500px or 1000px so that they are still usable if we need a little bigger size images. This will save upload bandwidth and may avoid upload limit on server.
- Serve the resized version of this original/resized image stored on server by using library such as https://github.com/WGBH/django-versatileimagefield. This gives a faster page load as profile image would be roughly 100px.

**Comment by vnbang2003** [comment]
@ultimatecoder Can you help us with this ?

**Comment by vnbang2003** [comment]
@staranjeet Can you help us with this ?

**Comment by staranjeet** [comment]
Ok, I will have a look then and  get back on this.

**Comment by staranjeet** [comment]
As @theskumar suggested above, we can use `versatileimagefield` to serve images at different resolutions. Now what should be the size for the resized image which we are going to save?

**Comment by vnbang2003** [comment]
@staranjeet  let make it 1 MB per image.
Please do even handle below usecase
 In case want to update existing profile we need to remove the old one from the filesystem and add new one

**Comment by staranjeet** [comment]
I have created a PR with my [master](https://github.com/staranjeet/wye/pull/3). This does not handles the case of update.

**Comment by vnbang2003** [comment]
@theskumar Can you please review it ?

**Comment by theskumar** [comment]
@vnbang2003 For issue with storage of original image on server, I would suggest to use client side resizing before upload, apart from resizing on the server side. User should be able to select a square crop area.

For server side deletion of old photo, just use the same file name for every upload of the profile image for a given person, make use of a unique identifier of a user. e.g. `id` [Since auto-increamented id's are used it's not safe to use them directly, so make use of [hashids](http://hashids.org/python/) to obfuscate them.

Note on implementation, @staranjeet see if you are able to 
1. Abstract out the resizing logic to a stateless, independent, reusable function that takes a image file object and resize value and returns a resized version of image.
2. Use `self.picture.height` and `self.picture.width` property before loading the image using PIL.
3. Don't use filename present in the uploaded file, generate and overwrite it server-side.

**Comment by theskumar** [comment]
@staranjeet Forget about my implementation notes, let's just use https://github.com/un1t/django-resized as drop in replacement for ImageField

**Comment by vnbang2003** [comment]
@staranjeet Any update on this PR please ?

**Comment by staranjeet** [comment]
[django-resized](https://github.com/un1t/django-resized) officially lists support upto Django 1.7. Also it was updated 10 months back. Should I use that or continue with my previous approach?

**Comment by vnbang2003** [comment]
@staranjeet Let use the update version library and fix the PR.

**Comment by vnbang2003** [comment]
@staranjeet Let start pushing a bit we need to release version 0.2 by Jan 25th.

**Comment by staranjeet** [comment]
I will definitely look into this week.

**Comment by vnbang2003** [comment]
Closing this for now . If we see similar issue please do reopen.
