### ISSUE TITLE
Think before manipulating/removing code 

### ISSUE THREAD

**Issue by shankisg** [pythonindia/wye#151]
Multiple instances I saw codes are getting removed or restructured without thinking on the impact.

- Instance one: Change in jquery import position in base.html, that effect the calendar widget in workshop create/update. Rather then working on real issue I figured out the issue and fixed that. https://github.com/pythonindia/wye/commit/88e6aaa40fe18a56ebf005b8a7f3b8f46a38120c

- Instance two: I had added message block in workshop list, as I don't want to effect whole app. Due to some reason that block was removed. https://github.com/pythonindia/wye/commit/efa802f9b8d25114392a8aee0da84537c33425fb#diff-4858b8eb2e51b69b0e6fb731592dbcc5

Suggestion: If you want to change or remove something, create an issue and ask the person why he/she had implemented that or ask to fix it or re implement it. It saves lot of time

**Comment by vnbang2003** [comment]
@shankisg Message block was removed by me as it was show very weird message. #127 .
If you can help fine to tune messages to be only for workshop level it would be great.

**Comment by vnbang2003** [comment]
For jquery issue i think you can add import in workshop list page itself by using extracss block.
{% block extracss %} {% endblock %}
This is avoid your scenarios someone else overwriting your preferred way to import jquery.

**Comment by shankisg** [comment]
After looking into #127 ,  it seems during login and logout some where in the code message.info(request, some message) is set. It is not getting displayed as their is no message block in any other page keeping the message in session, but in workshop we have message block, so its gets displayed here.

**Comment by shankisg** [comment]
@vnbang2003 

For beta, these problems could be fixed but for long run it might be a problem. So the label shouldn't be  **invalid**.

**Comment by vnbang2003** [comment]
@shankisg This is general discussion and just mark it as invalid issue. 
Once we get testcase fixed we will surely not hit the blockers due to others code changes as testcase itself will fail. 
Let do this add messages in the context object and display to avoid this scenarios. Let make it specific to workshop only.

**Comment by shankisg** [comment]
OK

**Comment by theskumar** [comment]
I personal recommendation would be to write tests for the features/bug fixes to avoid such instances. Given a pull-request to review, it's very hard to predict if it breaks something else somewhere. My 2 cents.

**Comment by ultimatecoder** [comment]
Well, I will be agree with @theskumar  that test cases are the only solution to find other breaks but I also believe that till system are finally working with agreed flow we should not begun for test cases. Because, with every development we have different vision and that might create modification in previous development. Once we are finalize with the system flow then and then test case should be begun.

@shankisg  On a node of breaking Date picker functionality I would like to apologize. I will appreciate little comment in code for notifying the importance of it. Thanks!
