### ISSUE TITLE
Adding new member in the organisation

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#168]
We need to allow college member to add new members to the system.
There are two option to add new members to the system
1) Existing user : Criteria to add existing member should be he belong to same location
           email template already there:/email_message/organisation/additional_member.html
2) New user: We need to send invite to new user saying person "x" has request you to join organization and ask him to complete profile. 
           email template: We need to add

**Comment by vnbang2003** [comment]
@ultimatecoder : Do you want to take it up . This is help you understand Organization module also ?

**Comment by vnbang2003** [comment]
@curioswati Can you help us with this ?

**Comment by curioswati** [comment]
Okay @vnbang2003 . I am doing it.

**Comment by curioswati** [comment]
@vnbang2003, as per my understanding, I am proposing the following way to fulfill the need:
I can either add a button like "Add members" on the org detail page that will take the user to another page having a form with two fields as:
"add existing member" : This will be a drop down containing names of the users that belong to the location of the org.
"add new member": A text box which will accept an email address of the new user to add, It could take multiple values in case user is adding multiple new users.

Or I could use the existing form that is used for updating org details and add the above mentioned fields.

Please give your views on it.

Questions:
1. In existing member case, the email is sent to the member who is adding a member, as the email template suggests. Should we not send an email to the user being added?
2. How would I make sure that the new member has signed up so that the member will be added up in the organization.

**Comment by vnbang2003** [comment]
@curioswati Good points. Let add new page as you suggested to keep it clean.
1. In existing member case, the email is sent to the member who is adding a member, as the email template suggests. Should we not send an email to the user being added?
---  We should send to both the parties, Regional lead on new member addition.
2. How would I make sure that the new member has signed up so that the member will be added up in the organisation.
--- If it new member we need to add him system and send confirmation email to new user asking him to confirm . Once user is confirm we will add him to the organisation.  We need to plan with user email confirmation objects.

Let me know if i answered you queries.

**Comment by curioswati** [comment]
@vnbang2003 , yes I got it. But the second answer is a bit confusing. Maybe I'll first reach that step and then try to clarify.

**Comment by vnbang2003** [comment]
Second point is invite user by email id. If you look at our testcase https://github.com/pythonindia/wye/blob/master/tests/functional/test_organsisation_flow.py
We add user and request them to click on confirm link .
That bring to next problem once user click on confirm link we should force him to reset password a bit complex flow. We should probably open new PR and work on it.

**Comment by curioswati** [comment]
@vnbang2003 , I am done with adding existing member case but I am stuck with the new user option. As It is still not clear how the flow goes with that. Could you please help. After filling the form, we will send mail to new member for confirmation. Now when it's done. How do I check that user has accepted the invitation? So that I can add her/him to organization and send the adder and regional lead the update.

**Comment by vnbang2003** [comment]
This is what is running in mind right now
1) Existing user invite user to join (We ask email, full name) this will work like signup page and make user inactive.
2) We create invited user profile and add him to organisation location and add him there.
3) Once user confirm the email confimraiton link we make him active and ask them to set password as we would have created his profile.
4) Next link on click confirm password in this case should to change password.

Is that make sense now ?

**Comment by curioswati** [comment]
Okay @vnbang2003 , got it. Summarizing:
So first I will send a mail to user being added with a link to signup page. Also create the user's profile setting her/him inactive and add her/him to organisation as well. When the user accepts the invitation and confirms subscription, It should be set active.

**Comment by curioswati** [comment]
@vnbang2003 is this issue still there? Although I am done fixing it, if it's not already resolved, I will create PR.

**Comment by vnbang2003** [comment]
@curioswati Please confirm it this is the Pull Request :https://github.com/pythonindia/wye/pull/235
I will close it once you confirm .

**Comment by curioswati** [comment]
No, @vnbang2003, it was for  #218. This one's different.
