### ISSUE TITLE
Connect Social Profiles

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/wye#180]
User A signs up with web form, verifies the email and logs out. Now, when the User A logs in using `Github`, `Google`, the user A is redirected to signup page with pre filled email address and other details. This experience is broken whereas User A should be logged in since email is already available.

Twitter doesn't provide email address after successful authentication. Once a user A is logged in, show an option to connect all accounts.

**Comment by vnbang2003** [comment]
@DESHRAJ Once more for you . Can you take it also ?

**Comment by DESHRAJ** [comment]
Hey @vnbang2003, @kracekumar  , I have resolved the first problem of logging the user directly when he tries to login through social account and he has signed up previously using simple registration form. The pull request https://github.com/pythonindia/wye/pull/187 contains the code. 

For resolving the twitter problem, I have a doubt. 
For instance user has already signed up and verified his email and logs out. Then he again tries to login through twitter, then do we need to show the account connection page where he can connect his social accounts to the single account ? But we are following the login through email so I am not sure how to login the user using username only that we get from twitter and then show the page where he can connect his twitter account with the normal account ? 

@kracekumar can you help me with this ? Please let me know if I am not clear in any point. 

One of the alternative that comes to my mind is to keep the authentication method as 'username_email' instead of 'email' only.

**Comment by kracekumar** [comment]
When a user logins in via `twitter`, page should display the option to `connect existing profile` or `create profile`.

### Case 1: Create profile

Create profile should take to normal page and post profile creation, `all auth/custom backend` should store connection between profile and twitter. Next time user logins with twitter, the correct profile is associated. All auth must take care of this.

### Case 2: Connect profile

On clicking this option, user will enter an email id and email should be triggered for verification. Once verification is successful, social account should be linked.

@DESHRAJ Have a look allauth docs https://django-allauth.readthedocs.org/en/stable/advanced.html

**Comment by kutuhal** [comment]
###Case 2a: Incorrect Email while connecting profile
Few points to consider.
- If user gives the mail for connecting and hasn't authenticated. But again logins with Twitter account. Should we show the usual awaiting authentication?
- If user accidentally gives incorrect email, what are his options to re-enter the correct email.

**Comment by kracekumar** [comment]
> If user gives an mail for connecting but before authenticating logins again with Twitter account. Should we show the usual awaiting authentication message?

Yes, similar to password reset/account verification.

> If user accidentally gives incorrect email, what are his/her options to re-enter the correct email?

`All auth` should provide an option to disconnect.

**Comment by DESHRAJ** [comment]
Ok sure. I will look into all these cases and will resolve this soon. I will ping you @kracekumar if need some help.

**Comment by vnbang2003** [comment]
@DESHRAJ Are you working on it

**Comment by DESHRAJ** [comment]
@vnbang2003 I am not working on it.
