### ISSUE TITLE
twitter message

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#191]
We need to change the twitter message to show details . The link is of not use as it will be visible only after login.
"
Python3 workshop at AboutHive-2-Bengaluru on 2015-11-28 confirmed! Details at http://beta.pythonexpress.in/workshop/1/
"
to

Received Python3 workshop request from <org> , <Locaiton> on date. Login to account and accept workshop if interested to conduct this workshop.

@harisibrahimkv Can you work on this ?

**Comment by harisibrahimkv** [comment]
@vnbang2003 With all due respect, I think the workshop details link should be public. The tweet does not make sense if it does not have a link to take people there.

**Comment by vnbang2003** [comment]
@harisibrahimkv I get your point but i still feel -1 for make it public.
Twitter handler is just to let them know workshop is requested. Making it public doesn't help as he can't selected workshop without creating profile.
Let show details only to serious guys who created account with us.

**Comment by harisibrahimkv** [comment]
@vnbang2003 I disagree with you.

The workshop details should be public so that anyone who sees the page can decide whether to sign up or not and decide whether to teach there or not.

Signing up/Logging in every now and then just to check for "workshops that require a tutor" is not a good idea.

In any case, the tweet message is a small change to be made. Since I don't see the point in not making the workshop details public, I won't be editing the Twitter message.

**Comment by vnbang2003** [comment]
I see valid point you made.  Let me rethink .
@theskumar @kirang89 What do you guys suggest ?

**Comment by kirang89** [comment]
@vnbang2003 I agree with @harisibrahimkv 

As a user, I would like to know all the details of the workshop (topic, agenda, venue) before I decide to attend it. Making me to signup just to see that adds inertia, so I'm likely to not do the same. 

I'd suggest keeping the details public but requiring them to login in order to register for the workshop. In doing so, we'll have to make it clear in the workshop details page that we require a user to register for the workshop in order to attend it.

**Comment by vnbang2003** [comment]
open issue #219 hence closing this
