### ISSUE TITLE
First workshop email

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/wye#363]
When a workshop is confirmed, a volunteer sends across templated introduction email to `tutor, POC`. This step can automate using Celery and Sendgrind and removes volunteer bottleneck.

Here is the email

"""
<Salutation>

Welcome aboard. PythonExpress would like to take the liberty of introducing the Trainer and Point of Contact for the workshop scheduled for <date> and on the <topic>.

Point of Contact: <name> <email> <phone>
The Trainer:  <name> <email> <phone>

<trainer>
please communicate your requirements for the workshop day to Manas.
Please feel free to take this discussion forward, preferably keeping <email> in the loop.

Let’s work towards a great workshop !
"""

**Comment by bhanuvrat** [comment]
Should the requirements / restrictions also be mentioned here, or should they be there before the POC submits the request.

basic requirement
 - decent Internet connection for every attendee.
 - Working Projector and screen.
 - adequate air conditioning systems.

restrictions:
 - Not more than 40 attendees in one room.
 - decent amplifier system with wireless mic if attendees > 25
 
et, el

Two of my workshops had > 100 people stuffed into one long room without adequate air-conditioning. They turned into hot, sweaty, boring seminars instead of hands-on workshops.
Mentioning them upfront should mitigate the problem.

**Comment by vnbang2003** [comment]
@bhanuvrat We can add in FAQ section.

**Comment by vnbang2003** [comment]
Closing this as fix it done for #301 and we have pull request for the same.(https://github.com/pythonindia/wye/pull/353)
