### ISSUE TITLE
Align forms fields

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye#63]
Some fields in workshop/organisation creation forms are left aligned and some fields are right aligned.

![w1](https://cloud.githubusercontent.com/assets/4463796/10647080/15c19a12-7854-11e5-9eeb-2b4043e5a377.png)

**Comment by vnbang2003** [comment]
yep this is because of autofill library usage. I saw it and probably work soon

**Comment by staranjeet** [comment]
@vnbang2003 : If anyone is not working on this, I can work on it.

**Comment by vnbang2003** [comment]
if you want to start work just leave comment saying you are working on it.

**Comment by mascot6699** [comment]
Its not because of autofill rather all text inputs have `float-right;` right now. and thus an override of css is needed. We need to write this in all places where text field will be generated by forms.

`<style>
    form input[type=text]{float:none;}
</style>`

But am not sure where to put this css. Puting it at 4 places (ie create and update html of organisation and workshop) seems repetitive. What code structure are we following for css? I have not clue of scss so maybe someone can just override at correct place.

**Comment by vnbang2003** [comment]
You can add css in app.css 
https://github.com/pythonindia/wye/blob/master/wye/static/css/app.css

**Comment by vnbang2003** [comment]
It been fixed. Hence closing it.
